language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "tolasom-github"
    token:
      secure: "wHNBj8gb/ZIVGds0Rs4g9H7CJhs4iMhLtLpYNaGOZU6G7dP+WZ6RDSdhzuG+0u1t5K/1XTU28OzManHvMe7VKH0C+BWTFcI1gx4yLfIkfxsIe2M0kqY7YTV/CNwzu5Lf0iDG3E3SGXbg7+0uDeGm6gLy87juMZViHY0/6FfQi8vsrJvmNBf2uUnjPnDmwXwr3Z9kH5xBZP46ETevTlK0q63LTfl3bu6BF4nINMyZQlEu4KxViSxSlhcnwKEsBHa7XJ8iK/V0exjrz6SO6yQZp9lTo3bJjLuZ58gJnfZNEfOI7nCoUZtwPjkNRvjG8sKweiLUmusbBd/iTTchIaAA+VZ05CWIWLakpipVTLRuluYzGpUxNFuEgyABWgqIDhEcYwSKoaVjv1K5Ky1g7uozXwt8XxVRUHCtlf1E1WwMfU7g4tQDRvchZTygvozkhpkgp/IMHzm0ZZvUFBO+CHXtHUB0WmYi3P0Cw2JGItE9o96rr0vnCz2EZc7dn0yF/B1idArhhf6wtk9S19akp7QNuMYpSLX7u3fy+R44V3F0wURwIbS/iydaXEeXDV9T/MCIGMRfmxBzPR3pxT+CHc7BomJZ96udCqNIfRtsVBZYkE9+TCvIMSavJcfiMafinKYqG/J7E0QdfMdT9lhCqxsW8BiJ2mV4Mp81eD04v3oCOpU="
jdk:
  - oraclejdk8 -X
  
script:
  - jdk_switcher use oraclejdk8
  - sonar-scanner -X
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
after_success:
  - "mvn org.jacoco:jacoco-maven-plugin:prepare-agent coveralls:report"
install:
  - "mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
jdk:
  - openjdk8
language: java
notifications:
  email:
    - somtola16@kit.edu.kh
script:
  - "mvn test jacoco:report"
notification:
  email: true